### PR TITLE
\leaders no longer supports \mskip

### PR DESCRIPTION
**Pull request by hansonchar**
Based on the latest [texbook.tex](https://ctan.org/tex-archive/systems/knuth/dist/tex/texbook.tex), `\leaders` no longer supports `\mskip`.

The reason for this pull request is to update TeXbyTopic.tex to stay consistent.

(See also the [relevant code](https://github.com/TeX-Live/texlive-source/blob/6281b57122cc534dfacfff8c050dbaea2869e66e/texk/web2c/luatexdir/tex/maincontrol.c#L1792-L1806) in TeX Live.)

### CODE REVIEW

**Comment by VictorEijkhout** [comment]
Can you point to specific lines in the TeXbook that state this? I downloaded Knuth's errata from ctan.org and they don't mention anything like this.

**Comment by hansonchar** [comment]
TeXbook p.290 where \mskip is explicitly excluded for use with \leaders:

**Comment by hansonchar** [comment]
Conincidentally I have a printed version of the old TeXbook, which incorporates the final corrections made in 1996, and it says "one of the six glue-appending commands", not "first five”.  However, when I looked at the latest texbook.tex  (line 18014-18018) downloaded from CTAN, it says first five, not six.  Furthermore, compared to the old TeXbook, the wordings have been changed from

  <leaders><box or rule><mathematical skip>

to

  <leaders><box or rule><horizontal skip>, deliberately avoiding the use of "mathematical".

This suggests \mskip was once supported back in the old days (1996), and then taken out for some reasons.

Regards,
Hansion

**Comment by hansonchar** [comment]
I just took a look at the [historic versions](https://ftp.math.utah.edu/pub/tex/historic/files/manuals/texbook/) of texbook.tex of [1995](https://ftp.math.utah.edu/pub/tex/historic/files/manuals/texbook/texbook.tex-1995), [1998](https://ftp.math.utah.edu/pub/tex/historic/files/manuals/texbook/texbook.tex-1998), [2008](https://ftp.math.utah.edu/pub/tex/historic/files/manuals/texbook/texbook.tex-2008), and the [latest](https://ctan.org/tex-archive/systems/knuth/dist/tex/texbook.tex).  Apparently the change from the use of `<mathematical skip>` to `<horizontal skip>` in `\leaders` was made since 2008.  Specifically,

## [texbook-1998.tex](https://ftp.math.utah.edu/pub/tex/historic/files/manuals/texbook/texbook.tex-1998)

(line 17966-17970)

> \\\<leaders>\<box or rule>\<mathematical skip>.\enskip\kern-.18pt
Here ^\<mathematical skip> refers to one of the six glue-appending commands
just mentioned; the formal syntax for \<leaders> and
for \<box or rule> is given in Chapter~24. A glue item that produces
^{leaders} is appended to the current list.

## [texbook-2008.tex](https://ftp.math.utah.edu/pub/tex/historic/files/manuals/texbook/texbook.tex-2008)

(line 17973-17977)

>\\\<leaders>\<box or rule>\<horizontal skip>.\enskip
Here ^\<horizontal skip> refers to one of the first five glue-appending
commands just mentioned; the formal syntax for \<leaders> and
for \<box or rule> is given in Chapter~24. A glue item that produces
^{leaders} is appended to the current list.

## Latest [texbook.tex](https://ctan.org/tex-archive/systems/knuth/dist/tex/texbook.tex)

(line 18014-18018)

>\\\<leaders>\<box or rule>\<horizontal skip>.\enskip
Here ^\<horizontal skip> refers to one of the first five glue-appending
commands just mentioned; the formal syntax for \<leaders> and
for \<box or rule> is given in Chapter~24. A glue item that produces
^{leaders} is appended to the current list.

**Comment by hansonchar** [comment]
I also found this change in [knuth-errata](https://ctan.org/tex-archive/systems/knuth/dist/errata).  Specifically, line 98-103:

>\bugonpage A290, lines 25--26 (02/24/08)
>
>\ninepoint\textindent{$\bull$}
\<leaders>\<box or rule>\<horizontal skip>.\enskip
Here \<horizontal skip> refers to one of the first five glue-appending
commands just mentioned; the formal syntax for \<leaders>\cutpar

**Comment by hansonchar** [comment]
Found this comment by Donald Knuth in [The TeX tuneup of 2008](https://tug.org/TUGboat/tb29-2/tb92knut.pdf):

>Leaders with \mskip glue never worked properly; this feature has now been disallowed.

**Comment by VictorEijkhout** [comment]
Ok, that’s a convincing one. I’ll approve your PR.

Victor.

From: Hanson Char ***@***.***>
Date: Wednesday, October 23, 2024 at 11:47
To: VictorEijkhout/tex-by-topic ***@***.***>
Cc: Victor Eijkhout ***@***.***>, Comment ***@***.***>
Subject: Re: [VictorEijkhout/tex-by-topic] leaders no longer supports mskip (PR #4)

Found this comment by Donald Knuth in The TeX tuneup of 2008<https://tug.org/TUGboat/tb29-2/tb92knut.pdf>:

Leaders with \mskip glue never worked properly; this feature has now been disallowed.

**Pull request merged**
